services:
  - type: web
    name: nestjs-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start:prod"
    envVars:
      - key: DATABASE_HOST
        value: localhost
      - key: DATABASE_PORT
        value: 3306
      - key: DATABASE_USERNAME
        value: mingnhee
      - key: DATABASE_PASSWORD
        value: 12070123Aa@
      - key: DATABASE_NAME
        value: flutterproject
    regions:
      - oregon
    databases:
      - databaseName: flutterproject
        type: mysql
        host: localhost
        username: mingnhee
        password: 12070123Aa@
        port: 3306
        sync: true
